---
- hosts: all
  tasks:
  - name: Add the user 'Adam Listek'
    ansible.builtin.user:
      name: testuser2
      comment: AdamListek
      uid: 1080
      createhome: yes
      home: /home/testuser2
